In [1]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [27]:

totalCalories = A.sum(axis=0) # axis=0 -> operação vertical, efetuada em colunas. axis=1 -> operação horizontal, efetuada em linhas
totalCalories = totalCalories.reshape(1,4) # Corrigindo o formato (4,) para (1,4)

print(f"Calorias:\t{totalCalories}\n")

Apercentage = A / totalCalories * 100

print(Apercentage)

Calorias:	[[ 59.  239.  155.4  76.9]]

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [32]:
A = np.array([[1],
              [2],
              [3],
              [4]])

B = 100 # O número é convertido para uma matriz (4,1)

print(f"A+B\n{A+B}\n")
print(f"A-B\n{A-B}\n")
print(f"A*B\n{A*B}\n")
print(f"A/B\n{A/B}\n")

A+B
[[101]
 [102]
 [103]
 [104]]

A-B
[[-99]
 [-98]
 [-97]
 [-96]]

A*B
[[100]
 [200]
 [300]
 [400]]

A/B
[[0.01]
 [0.02]
 [0.03]
 [0.04]]



In [33]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[100],    # A matriz é convertida para uma matriz (2, 3)
              [200]])

print(f"A+B\n{A+B}\n")
print(f"A-B\n{A-B}\n")
print(f"A*B\n{A*B}\n")
print(f"A/B\n{A/B}\n")

A+B
[[101 102 103]
 [204 205 206]]

A-B
[[ -99  -98  -97]
 [-196 -195 -194]]

A*B
[[ 100  200  300]
 [ 800 1000 1200]]

A/B
[[0.01  0.02  0.03 ]
 [0.02  0.025 0.03 ]]



In [35]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([100, 200, 300]) # A matriz é convertida para uma matriz(2, 3)

print(f"A+B\n{A+B}\n")
print(f"A-B\n{A-B}\n")
print(f"A*B\n{A*B}\n")
print(f"A/B\n{A/B}\n")

A+B
[[101 202 303]
 [104 205 306]]

A-B
[[ -99 -198 -297]
 [ -96 -195 -294]]

A*B
[[ 100  400  900]
 [ 400 1000 1800]]

A/B
[[0.01  0.01  0.01 ]
 [0.04  0.025 0.02 ]]



In [49]:
assert (A.shape == (2,3)) # Caso correto não gera erro
try:
    assert (A.shape == (1,3)) # Caso errado gera erro
finally:
    print()

AssertionError: 

In [50]:
A = np.random.randn(4,3)
B = np.random.randn(3,2)

print(A*B)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [51]:
np.exp?